---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-pod
  template:
    metadata:
      labels:
        app: auth-service-pod
    spec:
      containers:
        - name: auth-service
          image: maeljamin/ton-yugi-auth-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-service-config
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  labels:
      app: auth-service-svc
spec:
  selector:
    app: auth-service-pod # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Can be accessed inside the cluster

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  AUTH_SERVICE_PORT: "8000"
  AUTH_SERVICE_JWT_SECRET: "secret"
  AUTH_SERVICE_JWT_EXPIRATION: "2592000"
  AUTH_SERVICE_POSTGRES_HOST: "auth-service-db"
  AUTH_SERVICE_POSTGRES_PORT: "5432"
  AUTH_SERVICE_POSTGRES_DB: "auth_service"
  AUTH_SERVICE_POSTGRES_USER: "postgres"
  AUTH_SERVICE_POSTGRES_PASSWORD: "postgres"
