---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-pod
  template:
    metadata:
      labels:
        app: auth-service-pod
    spec:
      containers:
        - name: auth-service
          image: maeljamin/ton-yugi-auth-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: global-project-secrets
          resources:
            requests:
              memory: "270Mi"
              cpu: "30m"
            limits:
              memory: "270Mi"
              cpu: "30m"
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  labels:
      app: auth-service-svc
spec:
  selector:
    app: auth-service-pod # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Can be accessed inside the cluster
