version: "3.4"
services:
    gateway:
      build:
        context: ./server/gateway
        dockerfile: Dockerfile
        target: dev
      hostname: gateway
      command: >
        sh -c "yarn install &&
        yarn start:dev"
      env_file:
        - .env.dev
      depends_on:
        - card-service-node
        - user-service-node
      volumes:
        - ./server/gateway:/usr/src/app:cached
      ports:
        - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
      networks:
        - backend-dev
        - frontend-dev
    card-service-node:
      build:
        context: ./server/card-service
        dockerfile: Dockerfile
        target: dev
      hostname: card-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - card-service-postgres
      volumes:
        - ./server/card-service:/usr/src/app:cached
      links:
        - card-service-postgres
    card-service-postgres:
      image: postgres:13.2-alpine
      hostname: card-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${CARD_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${CARD_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${CARD_SERVICE_POSTGRES_DB}
      volumes:
        - card-service-postgres-dev:/var/lib/postgresql/data
    user-service-node:
      build:
        context: ./server/user-service
        dockerfile: Dockerfile
        target: dev
      hostname: user-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - user-service-postgres
      volumes:
        - ./server/user-service:/usr/src/app:cached
      links:
        - user-service-postgres
    user-service-postgres:
      image: postgres:13.2-alpine
      hostname: user-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${USER_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${USER_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${USER_SERVICE_POSTGRES_DB}
      volumes:
        - user-service-postgres-dev:/var/lib/postgresql/data
    payment-service-node:
      build:
        context: ./server/payment-service
        dockerfile: Dockerfile
        target: dev
      hostname: payment-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - payment-service-postgres
      volumes:
        - ./server/payment-service:/usr/src/app:cached
      links:
        - payment-service-postgres
    payment-service-postgres:
      image: postgres:13.2-alpine
      hostname: payment-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${PAYMENT_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${PAYMENT_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${PAYMENT_SERVICE_POSTGRES_DB}
      volumes:
        - payment-service-postgres-dev:/var/lib/postgresql/data
    auth-service-node:
      build:
        context: ./server/auth-service
        dockerfile: Dockerfile
        target: dev
      hostname: auth-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - auth-service-postgres
      volumes:
        - ./server/auth-service:/usr/src/app:cached
      links:
        - auth-service-postgres
    auth-service-postgres:
      image: postgres:13.2-alpine
      hostname: auth-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${AUTH_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${AUTH_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${AUTH_SERVICE_POSTGRES_DB}
      volumes:
        - auth-service-postgres-dev:/var/lib/postgresql/data
    adminer:
      image: adminer:4.8.1
      hostname: adminer
      networks:
        - backend-dev
      ports:
        - 9000:8080
networks:
  backend-dev:
    driver: bridge
  frontend-dev:
    external:
      name: infrastructure
volumes:
    card-service-postgres-dev:
    user-service-postgres-dev:
    payment-service-postgres-dev:
    auth-service-postgres-dev:
