version: "3.4"
services:
    ### FRONTEND GATEWAY ###
    gateway:
      build:
        context: ./server/gateway
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=gateway
      hostname: gateway
      command: >
        sh -c "yarn install &&
        yarn start:dev"
      env_file:
        - .env.dev
      depends_on:
        - card-service-node
        - user-service-node
      volumes:
        - gateway-dev:/usr/src/gateway
      ports:
        - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
      networks:
        - backend-dev
        - frontend-dev

    ### CARD SERVICE ###
    card-service-node:
      build:
        context: ./server/card-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=card-service
      hostname: card-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - card-service-postgres
      volumes:
        - card-service-node-dev:/usr/src/card-service
      links:
        - card-service-postgres
    card-service-postgres:
      image: postgres:13.2-alpine
      hostname: card-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${CARD_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${CARD_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${CARD_SERVICE_POSTGRES_DB}
      volumes:
        - card-service-postgres-dev:/var/lib/postgresql/data

    ### USER SERVICE ###
    user-service-node:
      build:
        context: ./server/user-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=user-service
      hostname: user-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - user-service-postgres
      volumes:
        - user-service-node-dev:/usr/src/user-service
      links:
        - user-service-postgres
    user-service-postgres:
      image: postgres:13.2-alpine
      hostname: user-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${USER_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${USER_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${USER_SERVICE_POSTGRES_DB}
      volumes:
        - user-service-postgres-dev:/var/lib/postgresql/data

    ### PAYMENT SERVICE ###
    payment-service-node:
      build:
        context: ./server/payment-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=payment-service
      hostname: payment-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - payment-service-postgres
      volumes:
        - payment-service-node-dev:/usr/src/payment-service
      links:
        - payment-service-postgres
    payment-service-postgres:
      image: postgres:13.2-alpine
      hostname: payment-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${PAYMENT_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${PAYMENT_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${PAYMENT_SERVICE_POSTGRES_DB}
      volumes:
        - payment-service-postgres-dev:/var/lib/postgresql/data

    ### AUTH SERVICE ###
    auth-service-node:
      build:
        context: ./server/auth-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=auth-service
      hostname: auth-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - auth-service-postgres
      volumes:
        - auth-service-node-dev:/usr/src/auth-service
      links:
        - auth-service-postgres
    auth-service-postgres:
      image: postgres:13.2-alpine
      hostname: auth-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${AUTH_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${AUTH_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${AUTH_SERVICE_POSTGRES_DB}
      volumes:
        - auth-service-postgres-dev:/var/lib/postgresql/data
    
    ### USER DECK SERVICE ###
    user-deck-service-node:
      build:
        context: ./server/user-deck-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=user-deck-service
      hostname: user-deck-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - user-deck-service-postgres
      volumes:
        - user-deck-service-node-dev:/usr/src/user-deck-service
      links:
        - user-deck-service-postgres
    user-deck-service-postgres:
      image: postgres:13.2-alpine
      hostname: user-deck-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${USER_DECK_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${USER_DECK_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${USER_DECK_SERVICE_POSTGRES_DB}
      volumes:
        - user-deck-service-postgres-dev:/var/lib/postgresql/data

    ### PROMO SERVICE ###
    promo-service-node:
      build:
        context: ./server/promo-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=promo-service
      hostname: promo-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - promo-service-postgres
      volumes:
        - promo-service-node-dev:/usr/src/promo-service
      links:
        - promo-service-postgres
    promo-service-postgres:
      image: postgres:13.2-alpine
      hostname: promo-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${PROMO_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${PROMO_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${PROMO_SERVICE_POSTGRES_DB}
      volumes:
        - promo-service-postgres-dev:/var/lib/postgresql/data

    ### DUEL SERVICE ###
    duel-service-node:
      build:
        context: ./server/duel-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
        args:
          - SERVICE_NAME=duel-service
      hostname: duel-service-node
      command: >
        sh -c "yarn install &&
        yarn typeorm:migrate &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - duel-service-postgres
      volumes:
        - duel-service-node-dev:/usr/src/duel-service
      links:
        - duel-service-postgres
    duel-service-postgres:
      image: postgres:13.2-alpine
      hostname: duel-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${DUEL_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${DUEL_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${DUEL_SERVICE_POSTGRES_DB}
      volumes:
        - duel-service-postgres-dev:/var/lib/postgresql/data

    ### MAILER SERVICE ###
    mailer-service-node:
      build:
        context: ./server/mailer-service
        dockerfile: ../../deploy/docker/Dockerfile
        target: dev
      hostname: mailer-service-node
      command: >
        sh -c "yarn install &&
        yarn start:dev"
      networks:
        - backend-dev
      env_file:
        - .env.dev
      depends_on:
        - mailcatcher
      volumes:
        - mailer-service-node-dev:/usr/src/app
      links:
        - mailcatcher

    ### ADMINER ###
    adminer:
      image: adminer:4.8.1
      hostname: adminer
      networks:
        - backend-dev
      ports:
        - 9000:8080

    ### MAILCATCHER ###
    mailcatcher:
      image: jderusse/mailcatcher:latest
      hostname: mailcatcher
      networks:
        - backend-dev
      ports:
        - 9025:80

networks:
  backend-dev:
    driver: bridge
  frontend-dev:
    external:
      name: infrastructure

volumes:
    card-service-postgres-dev:
    user-service-postgres-dev:
    payment-service-postgres-dev:
    auth-service-postgres-dev:
    user-deck-service-postgres-dev:
    promo-service-postgres-dev:
    duel-service-postgres-dev:
    gateway-dev:
    card-service-node-dev:
    user-service-node-dev:
    payment-service-node-dev:
    auth-service-node-dev:
    user-deck-service-node-dev:
    promo-service-node-dev:
    duel-service-node-dev:
    mailer-service-node-dev:

x-mutagen:
  sync:
    defaults:
      scanMode: accelerated
      ignore:
        vcs: true
        paths:
          - .DS_Store
          - .history
          - .idea
    
    ### GATEWAY VOLUMES SYNC ###
    gateway:
      alpha: ./server/gateway
      beta: volume://gateway-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    gateway-replica:
      alpha: volume://gateway-dev
      beta: ./server/gateway
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"
    
    ### CARD SERVICE VOLUMES SYNC ###
    card-service:
      alpha: ./server/card-service
      beta: volume://card-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    card-service-replica:
      alpha: volume://card-service-node-dev
      beta: ./server/card-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"

    ### USER SERVICE VOLUMES SYNC ###
    user-service:
      alpha: ./server/user-service
      beta: volume://user-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    user-service-replica:
      alpha: volume://user-service-node-dev
      beta: ./server/user-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"
    
    ### PAYMENT SERVICE VOLUMES SYNC ###
    payment-service:
      alpha: ./server/payment-service
      beta: volume://payment-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    payment-service-replica:
      alpha: volume://payment-service-node-dev
      beta: ./server/payment-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"
    
    ### AUTH SERVICE VOLUMES SYNC ###
    auth-service:
      alpha: ./server/auth-service
      beta: volume://auth-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    auth-service-replica:
      alpha: volume://auth-service-node-dev
      beta: ./server/auth-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"

    ### USER DECK SERVICE VOLUMES SYNC ###
    user-deck-service:
      alpha: ./server/user-deck-service
      beta: volume://user-deck-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    user-deck-service-replica:
      alpha: volume://user-deck-service-node-dev
      beta: ./server/user-deck-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"

    ### PROMO SERVICE VOLUMES SYNC ###
    promo-service:
      alpha: ./server/promo-service
      beta: volume://promo-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    promo-service-replica:
      alpha: volume://promo-service-node-dev
      beta: ./server/promo-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"

    ### DUEL SERVICE VOLUMES SYNC ###
    duel-service:
      alpha: ./server/duel-service
      beta: volume://duel-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    duel-service-replica:
      alpha: volume://duel-service-node-dev
      beta: ./server/duel-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"

    ### MAILER SERVICE VOLUMES SYNC ###
    mailer-service:
      alpha: ./server/mailer-service
      beta: volume://mailer-service-node-dev
      mode: two-way-resolved
      ignore:
        paths:
          - node_modules/
          - dist/
    mailer-service-replica:
      alpha: volume://mailer-service-node-dev
      beta: ./server/mailer-service
      mode: one-way-replica
      ignore:
        paths:
          - "*"
          - "!node_modules/**"
          - "!dist/**"