version: "3.4"
services:
    card-service-node:
      build:
        context: ./server/card-service
        dockerfile: Dockerfile
        target: prod
      networks:
        - server
      env_file:
        - .env
      ports:
        - "3001:3000"
      links:
        - card-service-postgres

    card-service-postgres:
      image: postgres:13.2-alpine
      networks:
        - server
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER_CARD_SERVICE}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_CARD_SERVICE}
        - POSTGRES_DB=${POSTGRES_DB_CARD_SERVICE}
      volumes:
        - card-service-postgres:/var/lib/postgresql/data

networks:
    server:
        driver: bridge

volumes:
    card-service-postgres: