version: "3.4"
services:
    gateway:
      build:
        context: ./server/gateway
        dockerfile: Dockerfile
        target: dev
      hostname: gateway
      env_file:
        - .env.dev
      volumes:
        - ./server/gateway:/usr/src/app
      ports:
        - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
      networks:
        - backend-dev
        - frontend-dev
    card-service-node:
      build:
        context: ./server/card-service
        dockerfile: Dockerfile
        target: dev
      hostname: card-service-node
      networks:
        - backend-dev
      env_file:
        - .env.dev
      volumes:
        - ./server/card-service:/usr/src/app
      links:
        - card-service-postgres
    card-service-postgres:
      image: postgres:13.2-alpine
      hostname: card-service-postgres
      networks:
        - backend-dev
      env_file:
        - .env.dev
      environment:
        - POSTGRES_USER=${CARD_SERVICE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${CARD_SERVICE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${CARD_SERVICE_POSTGRES_DB}
      volumes:
        - card-service-postgres-dev:/var/lib/postgresql/data

    adminer:
      image: adminer:4.8.1
      hostname: adminer
      networks:
        - backend-dev
      ports:
        - 9000:8080

networks:
  backend-dev:
    driver: bridge
  frontend-dev:
    external:
      name: infrastructure

volumes:
    card-service-postgres-dev: