---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: maeljamin/ton-yugi-payment-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: payment-service-config
          resources:
            requests:
              memory: "270Mi"
              cpu: "30m"
            limits:
              memory: "270Mi"
              cpu: "30m"
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
  type: ClusterIP # Can be accessed from outside the cluster

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PAYMENT_SERVICE_PORT: "8000"
  # PAYMENT_SERVICE_STRIPE_SUCCESS_URL:
  # PAYMENT_SERVICE_STRIPE_CANCEL_URL:
  PAYMENT_SERVICE_STRIPE_SECRET: "sk_test_51McULVLgiVx31Cexflc85gOsDRwpP76yqmC8gDu6iczrAchN47mkUOcoZYHa4XvPQM3lbXtbab3rupBFiGpOD2OB00DI4S7S9R"
  PAYMENT_SERVICE_POSTGRES_HOST: "payment-service-db"
  PAYMENT_SERVICE_POSTGRES_PORT: "5432"
  PAYMENT_SERVICE_POSTGRES_DB: "payment_service"
  PAYMENT_SERVICE_POSTGRES_USER: "postgres"
  PAYMENT_SERVICE_POSTGRES_PASSWORD: "postgres"
