---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: maeljamin/ton-yugi-payment-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: global-project-secrets
          resources:
            requests:
              memory: "270Mi"
              cpu: "30m"
            limits:
              memory: "270Mi"
              cpu: "30m"
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
  type: ClusterIP # Can be accessed from outside the cluster

