---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
        - name: gateway
          image: maeljamin/ton-yugi-gateway:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: API_GATEWAY_PORT
              value: "8000"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  selector:
    app: gateway-pod # which pods will receive the traffic
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  # type: LoadBalancer # Can be accessed from outside the cluster

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  labels:
    app: gateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
    rules:
      - http:
          paths:
            - path: /api(/|$)(.*)
              backend:
                serviceName: gateway-svc
                servicePort: 8000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  API_GATEWAY_PORT: "8000"
  CARD_SERVICE_PORT: "8000"
  USER_DECK_SERVICE_PORT: "8000"
  USER_SERVICE_PORT: "8000"
  AUTH_SERVICE_PORT: "8000"
  PAYMENT_SERVICE_PORT: "8000"
  MAILER_SERVICE_PORT: "8000"
  AUTH_SERVICE_HOST: "auth-service-svc"
  CARD_SERVICE_HOST: "card-service"
  DUEL_SERVICE_HOST: "duel-service"
  MAILER_SERVICE_HOST: "mailer-service"
  PAYMENT_SERVICE_HOST: "payment-service"
  PROMO_SERVICE_HOST: "promo-service"
  USER_DECK_SERVICE_HOST: "user-deck-service"
  USER_SERVICE_HOST: "user-service-svc"
