---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
        - name: gateway
          image: maeljamin/ton-yugi-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: API_GATEWAY_PORT
              value: "8000"

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  type: NodePort
  selector:
    app: gateway-pod # which pods will receive the traffic
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: default
  annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.global-static-ip-name: "gateway-ip"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: gateway-svc
            port:
              number: 8000


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  API_GATEWAY_PORT: "8000"
  CARD_SERVICE_PORT: "8000"
  USER_DECK_SERVICE_PORT: "8000"
  USER_SERVICE_PORT: "8000"
  AUTH_SERVICE_PORT: "8000"
  PAYMENT_SERVICE_PORT: "8000"
  MAILER_SERVICE_PORT: "8000"
  AUTH_SERVICE_HOST: "auth-service-svc"
  CARD_SERVICE_HOST: "card-service"
  DUEL_SERVICE_HOST: "duel-service"
  MAILER_SERVICE_HOST: "mailer-service"
  PAYMENT_SERVICE_HOST: "payment-service"
  PROMO_SERVICE_HOST: "promo-service"
  USER_DECK_SERVICE_HOST: "user-deck-service"
  USER_SERVICE_HOST: "user-service-svc"
