---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
  labels:
    app: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: user-service-db
          image: postgres:13.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "user_service"
          volumeMounts:
            - name: user-service-db-data
              mountPath: /var/lib/postgresql/data/user_service
      volumes:
        - name: user-service-db-data
          persistentVolumeClaim:
            claimName: user-service-db-data
---

apiVersion: v1
kind: Service
metadata:
  name: user-service-db
spec:
  selector:
    app: user-service-db # which pods will receive the traffic
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP # Can be accessed from other pods in the cluster
