---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: maeljamin/ton-yugi-user-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: user-service-config

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
  type: ClusterIP # Can be accessed from other pods in the cluster


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  USER_SERVICE_PORT: "8000"
  USER_SERVICE_POSTGRES_HOST: "user-service-db"
  USER_SERVICE_POSTGRES_PORT: "5432"
  USER_SERVICE_POSTGRES_USER: "postgres"
  USER_SERVICE_POSTGRES_PASSWORD: "postgres"
  USER_SERVICE_POSTGRES_DB: "user_service"
