publish:
	pnpm --filter insomniak-sdk-analytics run build
	pnpm --filter insomniak-sdk-analytics run types
	npm publish

build:
	pnpm --filter insomniak-sdk-analytics run build
	pnpm --filter insomniak-sdk-analytics run types