---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  labels:
    app: card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
        - name: card-service
          image: maeljamin/ton-yugi-card-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: card-service-config
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card-service # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
  type: ClusterIP # Can be accessed from other pods in the cluster

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: card-service-config
data:
  CARD_SERVICE_PORT: "8000"
  CARD_SERVICE_POSTGRES_HOST: "card-service-db"
  CARD_SERVICE_POSTGRES_PORT: "5432"
  CARD_SERVICE_POSTGRES_USER: "postgres"
  CARD_SERVICE_POSTGRES_PASSWORD: "postgres"
  CARD_SERVICE_POSTGRES_DB: "card_service"
  CARD_SERVICE_YUGIOH_API: "https://db.ygoprodeck.com/api/v7"
  CARD_SERVICE_YUGIOH_LANGUAGE: "fr"