version: "3"

services:
  node:
    image: node:19.0.0-alpine
    container_name: node_nest_app
    user: node
    stdin_open: true
    tty: true
    working_dir: /home/node
    environment:
      - NODE_ENV=development
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - "3000:3000"
    volumes:
        - .:/home/node
    networks:
      - nest_app_network

  postgres:
    image: postgres:13.2-alpine
    container_name: postgres_nest_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_app_yugi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

networks:
    nest_app_network: