---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
  labels:
    app: mailer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      containers:
        - name: mailer-service
          image: maeljamin/ton-yugi-mailer-service:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: mailer-service-config
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer-service # which pods will receive the traffic
  ports:
    - protocol: TCP
      port: 8000
  type: ClusterIP # Can be accessed from outside the cluster

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mailer-service-config
data:
  MAILER_SERVICE_PORT: "8000"
  WEBSITE_URL: ""
  MAILER_SERVICE_API_KEY: "MAILER_SERVICE_API_KEY=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"
  MAILER_SERVICE_USER: "yugioh-insomniak@no-reply.fr"
