name: Deploy Service "duel-service"

on:
  push:
    # branches:
      # - main
    paths:
      - "server/duel-service/**"
      - ".github/workflows/duel-service.yml"
      - "deploy/k8s/duel-service/**"
      - "deploy/scripts/**"
      - "deploy/docker/**"

  workflow_dispatch:
    inputs:
      route:
        description: 'Route'
        required: true
        default: 'user-service'

env:
  ## Docker Hub
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
  REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
  VERSION: ${{ github.sha }}
  LOCATION: ./server/duel-service

  ## Google Cloud Platform
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_REGION: ${{ secrets.GKE_REGION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:

  test-build-publish-deploy:
    name: Test, Build, Publish, Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        #
        # Tests the Service.
        #
      - name: Testing
        run: deploy/scripts/test-service.sh duel-service


        #
        # Authenticates with the Google Cloud Platform.
        #
      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        #
        # Sets up the Google Cloud SDK (gcloud).
        #
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl

        #
        # Configures the Kubernetes cluster.
        #
      - name: Configure Kubernetes cluster
        run: |
            gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.PROJECT_ID }}
            gcloud auth --quiet configure-docker
            kubectl config current-context

        #
        # Builds the Docker image.
        #
      - name: Build
        run: deploy/scripts/build-image.sh duel-service

        #
        # Publishes the Docker image to the container registry.
        #
      - name: Publish
        run: deploy/scripts/push-image.sh duel-service

        #
        # Deploys the Docker image to the Kubernetes cluster.
        #
      - name: Deploy Image
        run: deploy/scripts/deploy-image.sh duel-service

        #
        # Applies the Kubernetes files (test if a db.yml exists).
        #
      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deploy/k8s/duel-service/duel-service.yml
          if [ -f deploy/k8s/duel-service/duel-service-db.yml ]; then
            kubectl apply -f deploy/k8s/duel-service/duel-service-db.yml
          fi
