name: Deploy "gateway"

on:
  push:
    paths:
      - "server/gateway/**"
      - ".github/workflows/gateway.yml"

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
  REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  VERSION: ${{ github.sha }}


jobs:
  build-publish-deploy:
    name: Build, Publish, Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2


        #
        # Builds the Docker image.
        #
      - name: Build
        run: deploy/scripts/build-image.sh gateway

        #
        # Publishes the Docker image to the container registry.
        #
      - name: Publish
        run: deploy/scripts/push-image.sh gateway

        #
        # Authenticates with the Google Cloud Platform.
        #
      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        #
        # Sets up kubectl and gcloud
        #
        # - name: Set up kubectl
        #  run: |
        #    gcloud config set compute/zone $GKE_ZONE
        #    gcloud container clusters get-credentials $GKE_CLUSTER
        

        # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}







        #
        # Applies the Kubernetes files.
        #
      - name: Apply Kubernetes files
        run: |
            kubectl apply -f deploy/k8s/gateway/gateway.yml                        

        #
        # Deploys the Docker image to the Kubernetes cluster.
        #
      - name: Deploy
        run: deploy/scripts/deploy-image.sh gateway

