name: Deploy "mailer-service"

on:
  push:
    paths:
      - "server/mailer-service/**"
      - ".github/workflows/mailer-service.yml"
      - "deploy/k8s/mailer-service/**"
      - "deploy/scripts/**"
      - "deploy/docker/**"

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
  REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  VERSION: ${{ github.sha }}

jobs:

  test-build-publish-deploy:
    name: Test, Build, Publish, Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        #
        # Tests the Service.
        #
      - name: Testing
        run: deploy/scripts/test-service.sh mailer-service


        #
        # Authenticates with the Google Cloud Platform.
        #
      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        #
        # Sets up the Google Cloud SDK (gcloud).
        #
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl

        #
        # Configures Docker to use the Google Cloud Platform.
        #
      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Get the GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}


        #
        # Builds the Docker image.
        #
      - name: Build
        run: deploy/scripts/build-image.sh mailer-service

        #
        # Publishes the Docker image to the container registry.
        #
      - name: Publish
        run: deploy/scripts/push-image.sh mailer-service

        #
        # Deploys the Docker image to the Kubernetes cluster.
        #
      - name: Deploy Image
        run: deploy/scripts/deploy-image.sh mailer-service

        #
        # Applies the Kubernetes files (test if a db.yml exists).
        #
      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deploy/k8s/mailer-service/mailer-service.yml
          if [ -f deploy/k8s/mailer-service/mailer-service-db.yml ]; then
            kubectl apply -f deploy/k8s/mailer-service/mailer-service-db.yml
          fi
