name: Deploy "payment-service"

on:
  push:
    # branches:
      # - develop
    paths:
      - "server/payment-service/**"
      - ".github/workflows/payment-service.yml"
      - "deploy/k8s/payment-service/**"
      - "deploy/scripts/**"
      - "deploy/docker/**"

env:
  ## Docker Hub
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
  REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
  VERSION: ${{ github.sha }}
  LOCATION: ./server/payment-service

  ## Google Cloud Platform
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_REGION: ${{ secrets.GKE_REGION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:

  test-build-publish-deploy:
    name: Test, Build, Publish, Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        #
        # Tests the Service.
        #
      - name: Testing
        run: deploy/scripts/test-service.sh payment-service


        #
        # Authenticates with the Google Cloud Platform.
        #
      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        #
        # Sets up the Google Cloud SDK (gcloud).
        #
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl

        #
        # Configures the Kubernetes cluster.
        #
      - name: Configure Kubernetes cluster
        run: |
            gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.PROJECT_ID }}
            gcloud auth --quiet configure-docker
            kubectl config current-context

        #
        # Builds the Docker image.
        #
      - name: Build
        run: deploy/scripts/build-image.sh payment-service

        #
        # Publishes the Docker image to the container registry.
        #
      - name: Publish
        run: deploy/scripts/push-image.sh payment-service

        #
        # Deploys the Docker image to the Kubernetes cluster.
        #
      - name: Deploy Image
        run: deploy/scripts/deploy-image.sh payment-service

        #
        # Applies the Kubernetes files (test if a db.yml exists).
        #
      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deploy/k8s/payment-service/payment-service.yml
          if [ -f deploy/k8s/payment-service/payment-service-db.yml ]; then
            kubectl apply -f deploy/k8s/payment-service/payment-service-db.yml
          fi
